### ISSUE TITLE
[MacOS-크롬-1440-게시글상세조회페이지] 긴 댓글 작성 요청시 작성이 되지 않음

### ISSUE THREAD

**Issue by startupcodekr** [100-hours-a-week/2-hazel-park-community-fe#52]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 상세 조회로 이동
2. 댓글을 길게 작성 후 댓글 등록 버튼 클릭
3.  댓글이 안달리는 에러 보기

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.

댓글이 작성되며 댓글 개수가 늘어날 것으로 예상함

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

https://discord.com/channels/1240560508659175437/1316961242027655328/1316961363033325628

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: MacOS
 - Browser chrome
 - Version 131.0.6778.108(공식 빌드) (arm64)

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
댓글 수를 100자로 제한하는 기능을 추가하여 해당 이슈를 해결하였습니다 🙇🏻‍♀️

![무제](https://github.com/user-attachments/assets/dd5db157-07b3-4e00-80b5-b9cde7f3a604)
