### ISSUE TITLE
[MacOS-크롬-1440-게시글수정페이지] 게시글 수정페이지에 레이아웃이 정상적으로 보여지지 않음

### ISSUE THREAD

**Issue by startupcodekr** [100-hours-a-week/2-hazel-park-community-fe#53]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 상세조회로 이동
2. 수정 버튼 클릭
3. 에러 확인

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.

제목과 내용 입력창이 보여지며 기존 텍스트가 보여질 것으로 예상

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
<img width="967" alt="스크린샷 2024-12-13 오전 11 58 21" src="https://github.com/user-attachments/assets/dd141644-a5e9-46d4-af3e-03dc74743238" />

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: macOS
 - Browser chrome
 - Version 131.0.6778.108(공식 빌드) (arm64)
 
**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
게시글 내용 글자수를 1000자로 제한하여 해당 이슈를 해결하였습니다 🙇🏻‍♀️

![무제](https://github.com/user-attachments/assets/a4186699-1200-4fc8-863f-0806e25ab389)
