### ISSUE TITLE
[윈도우-크롬-1440-로그인페이지] 로그인 안됨 

### ISSUE THREAD

**Issue by gsandoo** [100-hours-a-week/2-hazel-park-community-fe#55]
**버그 설명**
로그인이 안되는데 확인 부탁드립니다

**재현하는 방법**
동작을 재현하는 단계:
1. 회원가입 페이지
2. 회원 정보 작성 후 가입 버튼 클릭
3. 로그인 페이지 이동
4. 로그인 안됨

**예상한 동작**
로그인이 안되는건지 회원가입이 안되는건지 확인부탁드립니다~

**스크린샷**
 
![image](https://github.com/user-attachments/assets/b0c1def2-fccd-4e9f-8da5-14fd5aefebb6)

**추가적인 내용:**
로그가 안보여 예측해보지만 회원가입 이미지 확장자 타입(gif, png 등)에 제한을 두어 alert 나 클라가 알 수 있는 플래그 던저주어 사용자에게 까지 전달되면 좋겠습니다

**Comment by gmlwlsdl** [comment]
![image](https://github.com/user-attachments/assets/8beebd3c-466e-40c2-8671-ed82695b2cd7)

산도! 계정은 만들어졌는데,, 혹시 지금도 로그인 안 되실까요? 🥹

**Comment by gmlwlsdl** [comment]
AWS ECR 인증 관련 오류였습니다! 크론탭으로 자동 갱신되도록 설정해두었습니다 🙇🏻‍♀️
#56 도 동일합니다.
