### ISSUE TITLE
[윈도우-크롬-1440-게시글작성페이지] 게시글 작성안됨 

### ISSUE THREAD

**Issue by gsandoo** [100-hours-a-week/2-hazel-park-community-fe#56]
**버그 설명**
게시글 작성이 안돼요

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 작성 후 게시물 리스트 화면 넘어가면 작성한 게시물 없음
2. 
3. 
4. 

**예상한 동작**
게시물 작성이 안된듯

**스크린샷**
![image](https://github.com/user-attachments/assets/b8c28595-eb6a-4039-93f6-6d4b1e868a8c)

**추가적인 내용:**
이전 이슈에 달아놓은 코멘트와 동일합니다

**Comment by gmlwlsdl** [comment]
AWS ECR 인증 관련 오류였습니다! 크론탭으로 자동 갱신되도록 설정해두었습니다 🙇🏻‍♀️
#55 와 동일합니다.
