### ISSUE TITLE
[윈도우-크롬-1440-회원정보수정페이지] 닉네임 중복 오류

### ISSUE THREAD

**Issue by gsandoo** [100-hours-a-week/2-hazel-park-community-fe#57]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:
1. 회원정보 수정 페이지 이동
2. 닉네임 수정 
3. 사진 입력
4.  수정하기 버튼 클릭

**예상한 동작**
닉네임 수정이 되어야 한다

**스크린샷**
 
![image](https://github.com/user-attachments/assets/3e9f4b3a-4dd6-4877-ad4f-277fc89b2630)

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
회원 정보 수정시에는 회원의 프로필 이미지와 닉네임 정보를 필요로 합니다.
당시 서버에서 ECR에 대한 인증이 풀려있어 이미지 데이터 처리에 오류가 있었습니다.
따라서 닉네임 수정도 원활하게 이루어지지 않았습니다. 이슈 반영해 두었습니다! 🙇🏻‍♀️
