### ISSUE TITLE
[OS-브라우저-1440-.] 닉네임 중복 가능 이슈

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-hazel-park-community-fe#58]
**버그 설명**
동일한 닉네임이 사용 가능한데 의도한 건가욤?

**재현하는 방법**
동작을 재현하는 단계:
1. 기존에 있는 닉네임으로 닉네임 변경

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.
-중복된 닉네임 사용 불가능하다 예상

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
![image](https://github.com/user-attachments/assets/ca17eb47-b45a-47dc-8bc2-3d379284a345)

**데스크톱(다음 정보를 작성해 주세요):**
 - chrome

**스마트폰(다음 정보를 입력하세요):**
\
**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
허허 의도하지 않았습니닷 ^₩^

**Comment by happy-yeachan** [comment]
심지어 같은 닉네임이면 다른 같은 닉네임 게시물도 수정 가능하군요 ㅇㅅㅇ
![image](https://github.com/user-attachments/assets/85985175-2c47-419d-ae25-7e04cbe975ac)

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
서버에서 닉네임 중복 확인 로직이 이루어지지 않아 발생한 이슈였습니다! 현재 수정 완료되었습니다 🙇🏻‍♀️

**Comment by happy-yeachan** [comment]
아직 중복 닉네임 적용이 가능한거 같은데 확인 부탁드릴게욤!
![image](https://github.com/user-attachments/assets/6dab2276-aaa6-47b9-a077-5c7e31d9334f)

**Comment by happy-yeachan** [comment]
![image](https://github.com/user-attachments/assets/df1a50aa-c4c6-46ca-ba42-c521a704dc3e)
동일하게 같은 닉네임은 수정이 가능합니다
