### ISSUE TITLE
[OS-브라우저-1225-게시글 수정 페이지] 권한이 없는 게시글 수정 가능 이슈

### ISSUE THREAD

**Issue by happy-yeachan** [100-hours-a-week/2-hazel-park-community-fe#59]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:
1. 주소창에 http://3.35.112.49/html/edit-post.html?id=33 입력하고 접근
2. 수정후 적용

**예상한 동작**
- 다른 사람이 작성한 게시글 수정창이 나오지 않아야 한다고 생각합니당

**스크린샷**
 문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
정구의 게시글을 수정한 모습
![image](https://github.com/user-attachments/assets/4b9a703b-ed67-4adc-a87e-3c6195f8b169)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
페이지 접근에 대한 제한 로직을 추가하였습니다! 현재 수정 완료되었습니다 🙇🏻‍♀️
