### ISSUE TITLE
회원가입에서 이메일 유효성 검사 이슈

### ISSUE THREAD

**Issue by pmsu2007** [100-hours-a-week/2-hazel-park-community-fe#62]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:

**예상한 동작**
제가 쓰고있는 이메일인데 유효성 검사에 실패했습니다.. ㅜ 
test@test.com은 통과하네요 !

**스크린샷**
![image](https://github.com/user-attachments/assets/29175e85-2168-41c1-8160-14826a6b8260)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
유효성 검사 로직에 숫자를 추가하였습니다! 현재 수정 완료되었습니다 🙇🏻‍♀️
