### ISSUE TITLE
게시글 이미지 이슈

### ISSUE THREAD

**Issue by pmsu2007** [100-hours-a-week/2-hazel-park-community-fe#63]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:

**예상한 동작**
이미지 전체가 보일 것으로 예상했지만, 짤림 이슈가 있습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/9005075b-21d6-4cda-ac15-e6db2b63b705)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
`width`를 지정한 뒤 `height`를 `auto`로 설정하여 전체 이미지가 보이도록 개선하였습니다! 현재 수정 완료되었습니다 🙇🏻‍♀️
