### ISSUE TITLE
URL로 타 게시글의 수정 페이지로 이동할 수 있는 이슈

### ISSUE THREAD

**Issue by pmsu2007** [100-hours-a-week/2-hazel-park-community-fe#64]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:

**예상한 동작**
post id로 제가 작성하지 않은 게시글의 수정 페이지로 이동이 가능합니다. 수정도 되네요 !

**스크린샷**

https://github.com/user-attachments/assets/95cffe37-636b-49f2-a1ad-c3bab0a22ae5

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
#59 와 동일한 이슈로, 페이지 접근에 대한 제한 로직을 추가하였습니다! 현재 수정 완료되었습니다 🙇🏻‍♀️
