### ISSUE TITLE
댓글 수 이슈

### ISSUE THREAD

**Issue by pmsu2007** [100-hours-a-week/2-hazel-park-community-fe#65]
**버그 설명**
버그에 대한 명확하고 간결한 설명해주세요.

**재현하는 방법**
동작을 재현하는 단계:

**예상한 동작**
댓글 수는 4로 되어있지만 실제 보이는 댓글은 3개 입니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/d4f79147-6722-42dc-845e-5ba4547e4f2c)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**스마트폰(다음 정보를 입력하세요):**
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
개발 과정에서 댓글이 중복 카운트되어 DB에 값이 잘못 저장되어 있었던 거 같습니다! 현재 수정 완료되었습니다 🙇🏻‍♀️
