### ISSUE TITLE
[window-chrome-2880px-게시글 상세] 로그인 미진행 시에도 게시글 상세 진입 가능한 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-hazel-park-community-fe#66]
**버그 설명**
로그인이 되어있지 않은 상태인데, 게시글 상세 페이지에 진입이 가능합니다.

**재현하는 방법**
동작을 재현하는 단계:
- http://52.79.154.1/html/post.html?id=43로 진입
- 좋아요 및 댓글 등록 진행

**예상한 동작**
로그인 화면으로 이동하거나 진입이 불가능할 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/33202e46-1205-4c19-94e4-50222de58c21)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
만약 의도적으로 진행하신거라면, 댓글 등록 및 좋아요를 클릭했을 때 로그인 화면으로 돌아가는건 어떤지 제안드려봅니다.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
미로그인한 유저가 해당 기능에 접근할시 로그인 페이지로 이동되도록 플로우를 개선하였습니다! 🙇🏻‍♀️
