### ISSUE TITLE
[window-chrome-2880px-게시글 상세] 댓글을 삭제할 시 뜨는 팝업 CSS

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-hazel-park-community-fe#68]
**버그 설명**
댓글 삭제 시 뜨는 팝업의 문구가 배율에 따라서 자유분방합니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 상세 페이지로 이동
2. 댓글 작성
3. 댓글 삭제

**예상한 동작**
배율에 상관없이 보여질 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/fc7f29d7-bc5c-4794-a6e7-ad7260f22f8f)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
기존의 vw, vh에서 px로 모달 크기를 고정하였습니다. 현재 해당 이슈 해결되었습니다 🙇🏻‍♀️
