### ISSUE TITLE
[window-chrome-2880px-게시글 상세] 게시글 상세 CSS가 어긋나는 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-hazel-park-community-fe#70]
**버그 설명**
게시글 상세 페이지의 CSS가 어긋나서 이상하게 보입니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 상세 페이지로 이동

**예상한 동작**
게시글 헤더, 게시글 내용, 댓글 내용의 CSS가 같은 라인에 있을 것 이라고 생각했습니다.

**스크린샷**
<img width="242" alt="image" src="https://github.com/user-attachments/assets/5298b169-113c-4c73-bd82-c5d205a7fa7b" />

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
해당 이슈 해결되었습니다 🙇🏻‍♀️
