### ISSUE TITLE
[window-chrome-2880px-비밀번호 수정] 비밀번호 수정시 helper-text CSS 노출 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-hazel-park-community-fe#72]
**버그 설명**
비밀번호 수정 시 hepler-text가 비밀번호 확인 란을 가립니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 비밀번호 수정 페이지로 이동

**예상한 동작**
가리지 않고 출력이 될 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/d77eeb2c-8181-4ff8-a550-957837baa814)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
현재 이슈 해결되었습니다 🙇🏻‍♀️
