### ISSUE TITLE
[window-chrome-2880px-비밀번호 수정] 비밀번호 수정 시 유효성 검사 관련 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-hazel-park-community-fe#73]
**버그 설명**
비밀번호 수정 시 아래 적힌 유효성 검사에 통과함에도 불구하고 helper-text가 출력됩니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 비밀번호 수정 페이지로 이동
2. Qwer1!@#$%^&* 비밀번호 입력

**예상한 동작**
heper-text가 출력되지 않을 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/6f6429b2-9efd-4d83-b0b7-2d6fafc7253b)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
유효성 검사에 더 많은 특수문자를 이용하는 방향으로 개선하였습니다! 해당 이슈 해결되었습니다 🙇🏻‍♀️
