### ISSUE TITLE
[window-chrome-2880px-비밀번호 수정] 비밀번호 수정 불가능 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-hazel-park-community-fe#74]
**버그 설명**
비밀번호 수정이 불가능합니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 비밀번호 수정 페이지로 이동
2. 비밀번호 입력
3. 비밀번호 수정 불가능

**예상한 동작**
비밀번호가 수정이 가능할 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/c9a5c85c-d38a-4802-9231-3a6332d9be6f)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
해당 이슈 수정되었습니다 🙇🏻‍♀️
