### ISSUE TITLE
[window-chrome-2880px-게시글 작성] 게시글 작성 시 출력되는 helper-text 이슈

### ISSUE THREAD

**Issue by dev-jeonggu** [100-hours-a-week/2-hazel-park-community-fe#75]
**버그 설명**
게시글 입력 내용이 1000자임에도 불구하고 helper-text가 없어지지 않습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 게시글 작성 페이지로 이동
2. 게시글 내용에 1000자 넘게 입력
3. 1000자 이후의 글자는 입력이 불가능 한 것으로 확인
4. helper-text 내용이 지워지지 않음

**예상한 동작**
1000자까지만 적히고 helper-text는 출력되지 않을 것이라고 생각했습니다.

**스크린샷**
![image](https://github.com/user-attachments/assets/042dbf94-32b1-4683-8a86-264975b1b318)

**데스크톱(다음 정보를 작성해 주세요):**

**스마트폰(다음 정보를 입력하세요):**

**추가적인 내용:**
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
기존에는 1000자를 초과할시 자동으로 내용이 잘리고 helper-text가 출력되게 설정해 두었습니다.
다만 이 부분이 사용자로 하여금 혼란을 야기할 수 있을 것으로 판단되어 helper-text를 제거, 1000자 작성시 붉은색으로 글자수를 보이는 방향으로 개선하였습니다 🙇🏻‍♀️

![image](https://github.com/user-attachments/assets/afabb107-c7bc-45e6-8035-9681d9834609)
