### ISSUE TITLE
[윈도우-1440-게시글상세] 게시글 상세 페이지 title Document 로 되어있습니다

### ISSUE THREAD

**Issue by gsandoo** [100-hours-a-week/2-hazel-park-community-fe#77]
**버그 설명**
게시글 상세 페이지 (http://52.79.154.1/html/post.html) 상단 title 명이 hazel -> Document 입니다
 
**재현하는 방법**

**예상한 동작**
예상했던 일에 대한 명확하고 간결한 설명해주세요.

**스크린샷**

**Comment by gmlwlsdl** [comment]
이슈 감사합니다 ☺️
현재 이슈 해결되었습니다 🙇🏻‍♀️
